#!/usr/bin/python3
import requests
import re

from argparse import ArgumentParser
from converter import converter
from datetime import datetime
from exceptions import InvalidFileExtension

# Getting current Norton Password Manager version
response = requests.get(
    "https://chrome.google.com/webstore/detail/norton-password-manager/admmjipmmciaobhojoghlmleefbicajg",
).text

if len(response) < 500 or response == None:
    raise TimeoutError("Unable to find Norton P.M latest version. Please retry")

version = re.search(r"(C-b-p-D-Xe h-C-b-p-D-md).*", response).group()[25:34]

# Norton autogenerated metadata
metadata = [
    {
        "Format": "BB633E3B-1DEC-47FC-9F9A-0301E80FE6C0",
        "Version": "2.0",
        "Product": "Norton Password Manager (Extension)",
        "Product Version": version,
        "Exported Date": datetime.now().strftime("%d-%m-%Y %H:%M:%S"),
    }
]

# Creating the argument parser
parser = ArgumentParser(
    prog="Kaspersky-Norton adapter",
    description="The following program is used to import credentials from Kaspersky Password Manager to Norton Password Manager. The program converts a TXT file into a correct/well-formatted CSV file readable from Norton Password Manager.",
)

parser.add_argument(
    "input",
    metavar="I",
    type=str,
    help="The parameter refers to the TXT file (exported from Kaspersky PM) containing the credentials",
)

if __name__ == "__main__":
    args = parser.parse_args()
    credentials: str = args.input

    if len(credentials) == 0 or credentials == None:
        raise FileNotFoundError("Invalid input file provided")

    if credentials.split(".")[1] != "txt":
        raise InvalidFileExtension(
            f'Invalid file extension. The input file is invalid or not supported ({credentials.split(".")[1]})'
        )

    converter(metadata, credentials)
    print(
        """Thanks for having used my program. The following script has been generated to be public and reusable, inspiring to a personal problem and the one described in the following forum: https://community.norton.com/en/forums/import-passwords-kaspersky
          
          Visit my website: https://salboh.xyz
          """
    )
